global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-server"
    static_configs:
      - targets: ["api:3000"]

  - job_name: "ai-service"
    static_configs:
      - targets: ["ai:8000"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "worker-service"
    static_configs:
      - targets: ["worker:8084"]
